"""Tests for CLAUDE.md generator."""

from cck.generator import generate_claude_md


def test_generate_header():
    """Generate header with project name."""
    context = {"project_name": "my-project"}
    output = generate_claude_md(context)

    assert "# my-project" in output
    assert "Auto-generated by" in output


def test_generate_overview():
    """Generate overview section."""
    context = {
        "project_name": "test",
        "project_type": "python",
        "languages": ["Python", "TypeScript"],
        "entry_points": ["main.py", "cli.py"],
    }
    output = generate_claude_md(context)

    assert "## Overview" in output
    assert "**Type**: python" in output
    assert "**Languages**: Python, TypeScript" in output
    assert "**Entry Points**: main.py, cli.py" in output


def test_generate_structure():
    """Generate directory structure section."""
    context = {
        "project_name": "test",
        "structure": ["src/", "  main.py", "tests/"],
    }
    output = generate_claude_md(context)

    assert "## Directory Structure" in output
    assert "src/" in output
    assert "tests/" in output


def test_generate_key_files():
    """Generate key files section."""
    context = {
        "project_name": "test",
        "key_files": [
            {"path": "README.md", "purpose": "Project documentation"},
            {"path": "Dockerfile", "purpose": "Container definition"},
        ],
    }
    output = generate_claude_md(context)

    assert "## Key Files" in output
    assert "`README.md`: Project documentation" in output
    assert "`Dockerfile`: Container definition" in output


def test_generate_commands():
    """Generate commands section."""
    context = {
        "project_name": "test",
        "build_commands": ["pip install -e .", "pytest", "make build (Makefile)"],
    }
    output = generate_claude_md(context)

    assert "## Commands" in output
    assert "pip install -e ." in output
    assert "pytest" in output
    # Commands with description should be commented
    assert "# make build (Makefile)" in output


def test_generate_conventions():
    """Generate conventions section."""
    context = {
        "project_name": "test",
        "conventions": ["Ruff configured", "snake_case file naming"],
    }
    output = generate_claude_md(context)

    assert "## Conventions" in output
    assert "- Ruff configured" in output
    assert "- snake_case file naming" in output


def test_generate_footer():
    """Generate footer with usage notes."""
    context = {"project_name": "test"}
    output = generate_claude_md(context)

    assert "## Notes for Claude Code" in output
    assert "Read this file at session start" in output
    assert "auto-generated" in output.lower()
