"""CLAUDE.md generator - Generate context file from scan results."""

from typing import Dict, Any
from datetime import datetime


def generate_claude_md(context: Dict[str, Any]) -> str:
    """Generate CLAUDE.md content from scanned context.

    Based on CB project insights:
    - What works: Structure with purpose, exact commands, explicit prohibitions
    - What doesn't work: Abstract descriptions, outdated commands, too much detail
    """
    sections = []

    # Header
    sections.append(_generate_header(context))

    # Project Overview
    sections.append(_generate_overview(context))

    # Directory Structure
    if context.get('structure'):
        sections.append(_generate_structure(context))

    # Key Files
    if context.get('key_files'):
        sections.append(_generate_key_files(context))

    # Commands
    if context.get('build_commands'):
        sections.append(_generate_commands(context))

    # Conventions
    if context.get('conventions'):
        sections.append(_generate_conventions(context))

    # Footer
    sections.append(_generate_footer())

    return '\n\n'.join(sections)


def _generate_header(context: Dict[str, Any]) -> str:
    """Generate header section."""
    name = context.get('project_name', 'Project')
    return f"""# {name}

> Auto-generated by [claude-context-keeper](https://github.com/takawasi/claude-context-keeper)
> Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"""


def _generate_overview(context: Dict[str, Any]) -> str:
    """Generate project overview."""
    lines = ["## Overview"]

    ptype = context.get('project_type', 'unknown')
    langs = context.get('languages', [])

    lines.append(f"\n**Type**: {ptype}")
    if langs:
        lines.append(f"**Languages**: {', '.join(langs)}")

    if context.get('entry_points'):
        lines.append(f"**Entry Points**: {', '.join(context['entry_points'])}")

    return '\n'.join(lines)


def _generate_structure(context: Dict[str, Any]) -> str:
    """Generate directory structure section."""
    lines = ["## Directory Structure", "", "```"]
    lines.extend(context['structure'])
    lines.append("```")
    return '\n'.join(lines)


def _generate_key_files(context: Dict[str, Any]) -> str:
    """Generate key files section."""
    lines = ["## Key Files", ""]

    for kf in context['key_files']:
        lines.append(f"- `{kf['path']}`: {kf['purpose']}")

    return '\n'.join(lines)


def _generate_commands(context: Dict[str, Any]) -> str:
    """Generate commands section."""
    lines = ["## Commands", "", "```bash"]

    for cmd in context['build_commands']:
        # Make commands copy-paste ready
        if '(' in cmd:
            # Has description like "cmd (source)"
            lines.append(f"# {cmd}")
        else:
            lines.append(cmd)

    lines.append("```")
    return '\n'.join(lines)


def _generate_conventions(context: Dict[str, Any]) -> str:
    """Generate conventions section."""
    lines = ["## Conventions", ""]

    for conv in context['conventions']:
        lines.append(f"- {conv}")

    return '\n'.join(lines)


def _generate_footer() -> str:
    """Generate footer with usage notes."""
    return """---

## Notes for Claude Code

- Read this file at session start to understand project context
- Key files listed above are primary working areas
- Use exact commands from Commands section (copy-paste ready)
- Check Conventions for style guidelines

*This file is auto-generated. Manual edits may be overwritten.*"""
